package view;

import java.awt.event.*;
import controller.LogInInterface;
import controller.Controller;
import controller.LogInProxy;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class LogInView extends javax.swing.JFrame implements LogInInterface, ActionListener {

	private Controller controller;
	
	public void start()
	{
		try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
		setVisible(true);
	}
    public LogInView() {
    	createComponents();
        initComponents();
        addComponentsToFrame();
        registerEventHandlers();
        controller = Controller.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void createComponents()
    {
    	MainPanel = new javax.swing.JPanel();
    	LogInLabel = new javax.swing.JLabel();
    	LogInInfo = new javax.swing.JLabel();
    	CPRLabel = new javax.swing.JLabel();
    	PasswordLabel = new javax.swing.JLabel();
    	SeparatorCPR = new javax.swing.JSeparator();
    	SeparatorPassword = new javax.swing.JSeparator();
        CPRTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JPasswordField();
        LogInButtonPanel = new javax.swing.JPanel();
        LogInButton = new javax.swing.JButton();
    }
    public void addComponentsToFrame()
    {
    	javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(LogInButtonPanel);
    	LogInButtonPanel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogInButton, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogInButton, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SeparatorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PasswordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PasswordTextField))
                            .addComponent(LogInInfo)
                            .addComponent(LogInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeparatorCPR, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(CPRLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CPRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(LogInButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LogInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LogInInfo)
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CPRLabel)
                            .addComponent(CPRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SeparatorCPR, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(PasswordLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparatorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogInButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
        MainPanel.requestFocusInWindow();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() 
    {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(34, 58, 96));
        LogInLabel.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        LogInLabel.setForeground(new java.awt.Color(240, 240, 240));
        LogInLabel.setText("Login");

        LogInInfo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        LogInInfo.setForeground(new java.awt.Color(240, 240, 240));
        LogInInfo.setText("Please insert the CPR and the password.");

        CPRLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        CPRLabel.setForeground(new java.awt.Color(240, 240, 240));
        CPRLabel.setText("CPR");

        PasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(240, 240, 240));
        PasswordLabel.setText("Password");

        CPRTextField.setText("(Enter CPR)");
        CPRTextField.setBackground(new java.awt.Color(34, 58, 96));
        CPRTextField.setFont(new java.awt.Font("Century Gothic", 0, 19));
        CPRTextField.setForeground(new java.awt.Color(240, 240, 240));
        CPRTextField.setBorder(null);
        CPRTextField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (CPRTextField.getText().equals("(Enter CPR)")) {
                	CPRTextField.setText("");
                	CPRTextField.setForeground(new java.awt.Color(240, 240, 240));
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (CPRTextField.getText().isEmpty()) {
                	CPRTextField.setForeground(new java.awt.Color(240, 240, 240));
                	CPRTextField.setText("(Enter CPR)");
                }
            }
         });

        PasswordTextField.setText("(Enter Password)");
        PasswordTextField.setBackground(new java.awt.Color(34, 58, 96));
        PasswordTextField.setFont(new java.awt.Font("Century Gothic", 0, 19));
        PasswordTextField.setForeground(new java.awt.Color(240, 240, 240));
        PasswordTextField.setBorder(null);
        PasswordTextField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (PasswordTextField.getText().equals("(Enter Password)")) {
                	PasswordTextField.setText("");
                	PasswordTextField.setForeground(new java.awt.Color(240, 240, 240));
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (PasswordTextField.getText().isEmpty()) {
                	PasswordTextField.setForeground(new java.awt.Color(240, 240, 240));
                	PasswordTextField.setText("(Enter Password)");
                }
            }
         });

        LogInButtonPanel.setBackground(new java.awt.Color(34, 58, 96));
        LogInButtonPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LogInButton.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LogInButton.setForeground(new java.awt.Color(34, 58, 96));
        LogInButton.setText("Login");
        LogInButton.setBorder(null);

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInButton;
    private javax.swing.JLabel LogInLabel;
    private javax.swing.JLabel LogInInfo;
    private javax.swing.JLabel CPRLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel LogInButtonPanel;
    private javax.swing.JSeparator SeparatorCPR;
    private javax.swing.JSeparator SeparatorPassword;
    private javax.swing.JTextField CPRTextField;
    private javax.swing.JPasswordField PasswordTextField;
    // End of variables declaration//GEN-END:variables
    
	
    private void registerEventHandlers(){
    	LogInButton.addActionListener(this);
    	PasswordTextField.addKeyListener(new KeyAdapter() {
    		public void keyPressed(KeyEvent e)
    		{
    			if(e.getKeyCode() == KeyEvent.VK_ENTER)
    			{
    				LogInButton.doClick();
    			}
    		}
		});
    }
    
    @Override
	public void actionPerformed(ActionEvent e) {
		if(e.getSource() == LogInButton)
		{
			String cpr = CPRTextField.getText();
			String pass = PasswordTextField.getText();
			controller.logIn(cpr, pass);
		}
	}
}

